version: '3.3'

services:
  mongodb:
    image: mongo
    command: mongod
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
    environment:
      - MONGO_INITDB_DATABASE=transfeera



